swagger: '2.0'
info:
  version: '1.0'
  title: "mvtest"
  description: mvtest is an API to manage exams.
  license:
    name: GPLv3
    url: https://github.com/CarlottaTagliaro/mvtest/blob/master/LICENSE
host: mvtestse.herokuapp.io
basePath: "/"
tags:
- name: Task
  description: Find everything about your tasks
- name: Exam
  description: Find everything about your exams
- name: Class
  description: Find everything about your classes
- name: Assignment
  description: Find everything about your assignments
- name: Submission
  description: Find everything about your submissions
- name: Review
  description: Find everything about your reviews  
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /tasks:
    get:
      tags:
      - "Task"
      summary: List all tasks the user has access to
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
          
    put:
      tags:
      - "Task"
      summary: Create a Task
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TaskRequest'
      responses:
        201:
          description: Task was created successfully
          schema:
            $ref: '#/definitions/Task'
            
  /tasks/{id}:
    #x-summary: Task
    get:
      tags:
      - "Task"
      summary: Find task by id
      #description: Returns a single task
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        description: ID of the task to return
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Task'
    post:
      tags:
      - "Task"
      summary: Edits a task
      #description: Edits a given task
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        description: ID of the task to edit
        required: true
        type: integer
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/TaskRequest'
      responses:
        200:
          description: Task was updated successfully
          schema:
            $ref: '#/definitions/Task'
    delete:
      tags:
      - "Task"
      summary: Deletes a task
      #description: Deletes a given task
      parameters:
      - name: id
        in: path
        description: ID of the task to delete
        required: true
        type: integer
      responses:
        204:
          description: Task was deleted successfully
  
  /exams:
    #x-summary: Exams Collection
    get:
      tags:
      - "Exam"
      summary: List all exams the user has access to
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Exam'
    put:
      tags:
      - "Exam"
      summary: Creates an exam
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Exam'
      responses:
        201:
          description: 'Created'
          schema:
            $ref: '#/definitions/Exam'
  /exams/{id}:
    get:
      tags:
      - "Exam"
      summary: Find exam by ID
      #description: Returns a single exam
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        description: ID of the exam to return
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Exam'
    delete:
      tags:
      - "Exam"
      summary: Deletes an exam
      #description: Deletes a given exam
      parameters:
      - name: id
        in: path
        description: ID of the exam to delete
        required: true
        type: integer
      responses:
        204:
          description: Deleted
    put:
      tags:
      - "Exam"
      #description: You may want to add a Task to an existing exam
      summary: Adds a Task to an Exam
      parameters:
      - name: id
        in: path
        description: ID of the exam to return
        required: true
        type: integer
      - in: body
        name: task id
        schema: 
          type: array
          items:
            type: number 
          example:
            - 1
            - 2
            - 3
      responses:
        202:
          description: 'Added'
          schema:
            $ref: '#/definitions/Exam'
  /exams/{id}/{id-task}:
    delete:
      tags:
      - "Exam"
      summary: Deletes a specific task in an exam
      #description: Deletes a specific task in an exam
      parameters:
      - name: id
        in: path
        description: ID of the exam to return
        required: true
        type: integer
      - name: id-task
        in: path
        required: true
        description: ID of the task to delete
        type: integer
      responses:
        204:
          description: Deleted

  /classes:
    #x-summary: Classes collection
    get:
      tags:
      - "Class"
      summary: Lists all classes the user belongs to
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Class'
    put:
      tags:
      - "Class"
      summary: Creates a new class
      produces:
      - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ClassRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Class'
  /classes/{id}:
    #x-summary: Classes collection
    get:
      tags:
      - "Class"
      summary: Find a class by ID
      parameters:
      - name: id
        in: path
        description: ID of the class to retrieve
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Class'
    post:
      tags:
      - "Class"
      summary: Edits a class
      parameters:
      - name: id
        in: path
        description: ID of the class to edit
        required: true
        type: integer
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/ClassRequest'
      responses:
        200:
          description: Class was successfully edited
          schema:
            $ref: '#/definitions/Class'
    delete:
      tags:
      - "Class"
      summary: Deletes a class
      parameters:
      - name: id
        in: path
        description: ID of the class to delete
        required: true
        type: integer
      responses:
        204:
          description: Class was deleted successfully.
          
  /assignment:
    #x-summary: Assignment Collection
    get:
      tags: 
      - Assignment
      summary: Get all assignments you've done
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Assignment'
    put: 
      tags:
      - "Assignment"
      summary: Creates a new assignment
      produces:
      - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AssignmentRequest'
      responses:
        201:
          description: The assignment was created successfully
          schema:
            $ref: '#/definitions/Assignment'
  /assignment/{id}:
    #x-summary: Assignment
    get:
      tags:
      - "Assignment"
      summary: Find assignment by id
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        description: ID of the assignment to return
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Assignment'
    post:
      tags:
      - "Assignment"
      summary: Edits an assignment
      #description: Edits a given assignment
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        description: ID of the assignment to edit
        required: true
        type: integer
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AssignmentRequest'
      responses:
        200:
          description: Assignment was updated successfully
          schema:
            $ref: '#/definitions/Assignment'
    delete:
      tags:
      - "Assignment"
      summary: Deletes an assignment
      parameters:
      - name: id
        in: path
        description: ID of the assignment to delete
        required: true
        type: integer
      responses:
        204:
          description: Assignment was deleted successfully

  /submission:
    #x-summary: Submission Collection
    get:
      tags: 
      - Submission
      summary: Get all submission you've done
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Submission'
    post: #post cause we have to store all the submission, it is not possible to modify them
      tags:
      - Submission
      summary: Create a new submission
      produces: 
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/SubmissionRequest'
      responses:
        200:
          description: Submission was created successfully
          schema:
            $ref: '#/definitions/Submission'
  /submission/{assign-id}:
    get:
      tags:
      - Submission
      summary: Retrieves all submission for a certain assignment
      produces:
        - application/json
      parameters:
      - name: assign-id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Submission'
    delete:
      tags:
      - Submission
      summary: deletes all submission for a certain assignment #retire
      parameters:
      - name: assign-id
        in: path
        required: true
        type: integer
      responses:
        204:
          description: submissions were deleted successfully

  /review:
    #x-summary: Review Collection
    get:
      tags:
      - Review
      summary: Get all reviews you've done
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Review'
    put:
      tags:
      - Review
      summary: Create a new review
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true  
        schema:
          $ref: '#/definitions/ReviewRequest'
      responses:
        201:
          description: Review was created successfully
          schema:
            $ref: '#/definitions/Review'
  /review/{id}:
    post:
      tags:
      - Review
      summary: Edit a specific review
      produces: 
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: number
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/ReviewRequest'
      responses:
        200:
          description: Review was updated successfully
          schema:
            $ref: '#/definitions/Review'

definitions:
  Task:
    title: Task
    type: object
    properties:
      id:
        type: number
      question:
        type: string
      choices:
        type: array
        items:
          type: string
      users:
        type: array
        items:
          $ref: '#/definitions/UserPerms'
    required:
      - id
      - question
      - choices
    example:
      id:  0
      question: Example question
      type: 1
      choices:
        - First Answer
        - Second Answer
        - Third Answer
        - Fourth Answer
      users:
        - email: "owner@mail.com"
          owner: true
          canWrite: true
        - email: "user@mail.com"
          owner: false
          canwrite: false
 
  User:
    title: User
    type: object
    properties:
      email:
        type: string
        format: email
      name:
        type: string

  ClassRequest:
    title: ClassRequest
    type: object
    properties:
      name:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/User'
    example:
      name: Software Engeneering
      users:
      - email: student@mail.com
        name: Good Student

  Class:
    title: Class
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/User'
    example:
      id: 0
      name: Software Engeneering
      users:
      - email: student@mail.com
        name: Good Student

  Exam:
    title: Exam
    type: object
    properties: 
      id:
        type: number
      owner:
          $ref: '#/definitions/User'
      tasks:
        type: array
        items:
          type: number
    example:
      id: 0
      owner:
        email: g.s@agg.it
        name: Mario
      tasks:
        - 0
        - 1
      
  UserPerms:
    title: User Perms
    type: object
    properties:
      email:
        type: string
      owner:
        type: boolean
      canWrite:
        type: boolean
  
  TaskRequest:
    title: Task Request
    type: object
    properties:
      question:
        type: string
      choices:
        type: array
        items:
          type: string
    required:
      - question
      - choices
    example:
      question: Example Question
      choices:
        - First Answer
        - Second Answer
        - Third Answer
        - Fourth Answer

  AssignmentRequest:
    title: AssignmentRequest
    type: object
    properties: 
      deadline:
        type: string
        format: date-time
      review:
        type: boolean
      TA:
        $ref: '#/definitions/User'
      class:
        type: array
        items:
          $ref: '#/definitions/Class'
    example:
      deadline: 12-12-2018
      review: true
      TA: 
        email: g.s@agg.it
        name: Mario
      class:
      - id: 0
        name: Software Engeneering
        users:
        - email: student@mail.com
          name: Good Student

  Assignment:
    title: Assignment
    type: object
    properties: 
      id:
        type: number
      deadline:
        type: string
        format: date-time
      review:
        type: boolean
      TA:
        $ref: '#/definitions/User'
      class:
        type: array
        items:
          $ref: '#/definitions/Class'
    example:
      id: 0
      deadline: 12-12-2018
      review: true
      TA: 
        email: g.s@agg.it
        name: Mario
      class:
      - id: 0
        name: Software Engeneering
        users:
        - email: student@mail.com
          name: Good Student

  SubmissionRequest:
    title: SubmissionRequest
    type: object
    properties:
      answer:
        type: string
      time:
        type: string
        format: date-time
      task-id: 
        type: number
      Author: 
        $ref: '#/definitions/User' #is the id enough?
      assignment-id:
        type: number
    example:
      answer: the correct answer is number 2
      time: 12-12-2018
      task-id: 3
      Author:
        email: g.s@agg.com
        name: Giovanni Storti
      assignment-id: 4

  Submission:
    title: Submission
    type: object
    properties:
      id:
        type: number
      answer:
        type: string
      time:
        type: string
        format: date-time
      task-id: 
        type: number
      Author: 
        $ref: '#/definitions/User' #is the id enough?
      assignment-id:
        type: number
    example:
      id: 0
      answer: the correct answer is number 2
      time: 12-12-2018
      task-id: 3
      Author:
        email: g.s@agg.com
        name: Giovanni Storti
      assignment-id: 4

  ReviewRequest:
    title: ReviewRequest
    type: object
    properties:
      submission-id:
        type: number
      author:
        $ref: '#/definitions/User'
      mark:
        type: number
      comment:
        type: string
    example:
      submission-id : 1 
      author:
        email: g.s@agg.com
        name: Giovanni Storti
      mark: 27
      comment: good work, well done

  Review:
    title: Review
    type: object
    properties:
      id: 
        type: number
      submission-id:
        type: number
      author:
        $ref: '#/definitions/User'
      mark:
        type: number
      comment:
        type: string
    example:
      id: 0
      submission-id : 1 
      author:
        email: g.s@agg.com
        name: Giovanni Storti
      mark: 27
      comment: good work, well done
