CREATE DATABASE IF NOT EXISTS MVTEST_DB;

CREATE TABLE IF NOT EXISTS EXAM(
  ID AUTO INCREMENT NOT NULL,
  DATETIME DEADLINE NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TASK(
  ID AUTO INCREMENT NOT NULL,
  TEXT VARCHAR(2500) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS OWN_TASK(
  ID_TASK INTEGER NOT NULL,
  ID_TA INTEGER NOT NULL,
  FOREIGN KEY (ID_TASK) REFERENCES TASK(ID),
  FOREIGN KEY (ID_TA) REFERENCES TA(ID)
);

CREATE TABLE IF NOT EXISTS OWN_EXAM(
  ID_EXAM INTEGER NOT NULL,
  ID_TASK INTEGER NOT NULL,
  FOREIGN KEY (ID_EXAM) REFERENCES EXAM(ID),
  FOREIGN KEY (ID_TASK) REFERENCES TASK(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORY(
  ID AUTO INCREMENT NOT NULL,
  NAME 
);

CREATE TABLE IF NOT EXISTS TA(
  ID AUTO INCREMENT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS STUDENT(
  ID AUTO INCREMENT NOT NULL,
  PRIMARY KEY(ID)
);

